export const LOGIN = "Log_In";
export const LOGIN_ERR = "Log_In_Err";

export const SELECT_METERIAL = "SELECT_METERIAL";
export const SELECT_METERIAL_ERR = "SELECT_METERIAL_ERR";
export const ADD_METERIAL = "ADD_METERIAL";
export const DELETE_METERIAL = "DELETE_METERIAL";
export const UPDATE_METERIAL = "UPDATE_METERIAL";

export const SELECT_MILKTEA = "SELECT_MILKTEA";
export const SELECT_MILKTEA_ERR = "SELECT_MILKTEA_ERR";
export const ADD_MILKTEA = "ADD_MILKTEA";
export const DELETE_MILKTEA = "DELETE_MILKTEA";
export const UPDATE_MILKTEA = "UPDATE_MILKTEA";
