export const LOGIN = "Log_In";
export const LOGIN_ERR = "Log_In_Err";

export const SELECT_METERIAL = "SELECT_METERIAL";
export const SELECT_METERIAL_ERR = "SELECT_METERIAL_ERR";
export const ADD_METERIAL = "ADD_METERIAL";
export const DELETE_METERIAL = "DELETE_METERIAL";
export const UPDATE_METERIAL = "UPDATE_METERIAL";

export const SELECT_MILKTEA = "SELECT_MILKTEA";
export const SELECT_MILKTEA_ERR = "SELECT_MILKTEA_ERR";
export const ADD_MILKTEA = "ADD_MILKTEA";
export const DELETE_MILKTEA = "DELETE_MILKTEA";
export const UPDATE_MILKTEA = "UPDATE_MILKTEA";

export const ADD_BILL = "ADD_BILL";
export const SHOW_PREPARE = "SHOW_PREPARE";
export const SELECT_BILL = "SELECT_BILL";
export const SELECT_BILL_ERR = "SELECT_BILL_ERR";
export const SELECT_DETAIL_BILL = "SELECT_DETAIL_BILL";
export const SELECT_DETAIL_BILL_ERR = "SELECT_DETAIL_BILL_ERR";

export const SELECT_PRODUCT = "SELECT_PRODUCT";
export const SELECT_PRODUCT_ERR = "SELECT_PRODUCT_ERR";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
